create table radical (
    id bigint generated by default as identity primary key,
    character varchar(8) not null unique,
    name_japanese varchar(100), name_romaji varchar(100), meaning varchar(500),
    stroke_count integer, position_name varchar(100), image_filename varchar(255),
    important boolean not null default false
);
create table kanji (
    id bigint generated by default as identity primary key,
    character varchar(8) not null unique, meaning varchar(1000) not null,
    onyomi varchar(500), kunyomi varchar(500), frequency_rank integer not null,
    jlpt_level varchar(4), jlpt_estimated boolean not null default true, grade integer,
    mnemonic varchar(2000), primary_radical_id bigint references radical(id)
);
create table component (
    id bigint generated by default as identity primary key,
    character varchar(8) not null unique, meaning varchar(500), radical_id bigint references radical(id)
);
create table kanji_component (
    kanji_id bigint not null references kanji(id) on delete cascade,
    component_id bigint not null references component(id), display_order integer not null,
    primary key (kanji_id, component_id)
);
create table word (
    id bigint generated by default as identity primary key,
    expression varchar(255) not null, reading varchar(500), meaning varchar(2000) not null,
    frequency_rank integer, unique(expression, reading)
);
create table kanji_word (
    kanji_id bigint not null references kanji(id) on delete cascade,
    word_id bigint not null references word(id) on delete cascade,
    contribution varchar(1000), display_order integer not null,
    primary key (kanji_id, word_id)
);
create table sentence (
    id bigint generated by default as identity primary key,
    japanese varchar(3000) not null unique, reading varchar(3000), english varchar(3000) not null,
    source_name varchar(100), source_key varchar(255)
);
create table kanji_sentence (
    kanji_id bigint not null references kanji(id) on delete cascade,
    sentence_id bigint not null references sentence(id) on delete cascade,
    primary key (kanji_id, sentence_id)
);
create index idx_kanji_frequency on kanji(frequency_rank);
create index idx_word_expression on word(expression);
create index idx_radical_meaning on radical(meaning);
