// Original starter sentences. Other words retain the source dictionary examples.
// Surrounding language uses kana so context does not introduce hidden kanji prerequisites.
export const WORD_CONTEXTS: Record<string, [string, string]> = {
  '予算': ['予算がたりないので、けいかくをかえます。', 'We will change the plan because the budget is insufficient.'],
  '予備': ['ねんのため、予備のかぎをもっていきます。', 'I will take a spare key just in case.'],
  '天気予報': ['天気予報によると、あしたはあめです。', 'According to the weather forecast, it will rain tomorrow.'],
  '仕事': ['仕事がおわってから、ともだちにあいます。', 'I will meet a friend after finishing work.'],
  '仕方': ['このどうぐのつかいかたではなく、なおす仕方をしりたいです。', 'I want to know how to fix this tool, rather than how to use it.'],
  '仕方がない': ['でんしゃがおくれているので、まつしか仕方がない。', 'The train is delayed, so there is nothing to do but wait.'],
  '他人': ['他人のいけんもきくことがたいせつです。', 'It is important to listen to other people’s opinions too.'],
  '写真': ['りょこうでとった写真をみせてもらいました。', 'Someone showed me the photographs they took on their trip.'],
  '去年': ['去年より、にほんごがわかるようになりました。', 'I can understand Japanese better than last year.'],
  '番号': ['よばれた番号をかくにんしてください。', 'Please check the number that was called.'],
  '信号': ['信号がかわるまで、ここでまってください。', 'Please wait here until the traffic light changes.'],
  '中央': ['えきの中央に、あんないじょがあります。', 'There is an information desk in the center of the station.'],
  '一年生': ['わたしは一年生です。', 'I am a first-year student.'],
  '一番': ['これが一番すきです。', 'I like this one the most.'],
  '一度': ['もう一度おねがいします。', 'One more time, please.'],
  '二時間': ['二時間べんきょうします。', 'I will study for two hours.'],
  '二月': ['たんじょうびは二月です。', 'My birthday is in February.'],
  '三人': ['三人でいきます。', 'The three of us will go.'],
  '三時': ['三時にあいましょう。', 'Let’s meet at three o’clock.'],
  '三枚': ['きっぷを三枚ください。', 'Three tickets, please.'],
  '四月': ['四月ににほんへいきます。', 'I will go to Japan in April.'],
  '五月': ['五月はあたたかいです。', 'May is warm.'],
  '五階': ['へやは五階です。', 'The room is on the fifth floor.'],
  '六時': ['六時におきます。', 'I get up at six o’clock.'],
  '七時': ['七時にあさごはんをたべます。', 'I eat breakfast at seven o’clock.'],
  '八月': ['八月はあついです。', 'August is hot.'],
  '十': ['りんごが十あります。', 'There are ten apples.'],
  '本': ['この本をよみます。', 'I will read this book.'],
  '川': ['川のそばをあるきます。', 'I walk beside the river.'],
  '来月': ['来月りょこうします。', 'I will travel next month.'],
  '月曜日': ['月曜日にあいましょう。', 'Let’s meet on Monday.'],
  '火曜日': ['火曜日はやすみです。', 'Tuesday is a day off.'],
  '水曜日': ['水曜日にでんわします。', 'I will call on Wednesday.'],
  '木曜日': ['木曜日にかえります。', 'I will return on Thursday.']
};
