import { Lesson } from '../models/learning.models';

export const DEMO_LESSONS: Lesson[] = [
  {id:'r-person',order:1,type:'RADICAL',title:'The person radical',japanese:'人',reading:'ひと',meaning:'person',explanation:'A simple figure walking on two legs. It often hints that a kanji is connected to people.',radicals:[{character:'人',meaning:'person',mnemonic:'Picture two legs walking forward.'}]},
  {id:'r-sun',order:2,type:'RADICAL',title:'The sun radical',japanese:'日',reading:'ひ',meaning:'sun / day',explanation:'A window framing the sun. It appears in words about light, time and days.',radicals:[{character:'日',meaning:'sun',mnemonic:'The sun is boxed into a bright window.'}]},
  {id:'k-rest',order:3,type:'KANJI',title:'A person rests',japanese:'休',reading:'やす・む',meaning:'rest',explanation:'A person leans against a tree. Put the two pictures together: rest.',radicals:[{character:'亻',meaning:'person',mnemonic:'A person standing side-on.'},{character:'木',meaning:'tree',mnemonic:'Branches grow from a trunk.'}]},
  {id:'k-bright',order:4,type:'KANJI',title:'Sun and moon',japanese:'明',reading:'あか・るい / めい',meaning:'bright',explanation:'The sun and moon combine their light, making everything bright and clear.',radicals:[{character:'日',meaning:'sun',mnemonic:'A framed sun.'},{character:'月',meaning:'moon',mnemonic:'A crescent moon with two clouds.'}]},
  {id:'k-school',order:5,type:'KANJI',title:'Learning at school',japanese:'学',reading:'まな・ぶ / がく',meaning:'study',explanation:'A child under a decorated roof receives knowledge. You will see 学 in 学生 and 学校.',radicals:[{character:'子',meaning:'child',mnemonic:'A child with arms spread.'},{character:'⺍',meaning:'small rays',mnemonic:'Little sparks of knowledge.'}]},
  {id:'s-rest',order:6,type:'SENTENCE',title:'Read your first sentence',japanese:'私は休みます。',reading:'わたし は やすみます。',meaning:'I rest.',explanation:'は marks 私 as the topic. 休みます is the polite form of 休む.',radicals:[{character:'亻',meaning:'person',mnemonic:'The person clue inside 休.'},{character:'木',meaning:'tree',mnemonic:'The tree supporting the person.'}]},
  {id:'s-bright',order:7,type:'SENTENCE',title:'Describe the morning',japanese:'朝は明るいです。',reading:'あさ は あかるい です。',meaning:'The morning is bright.',explanation:'明るい is an い-adjective. です makes the sentence polite.',radicals:[{character:'日',meaning:'sun',mnemonic:'Sun brings morning light.'},{character:'月',meaning:'moon',mnemonic:'Moon completes 明.'}]},
  {id:'p-school',order:8,type:'PASSAGE',title:'A small daily story',japanese:'私は学生です。朝、学校へ行きます。午後は家で休みます。',reading:'わたし は がくせい です。あさ、がっこう へ いきます。ごご は いえ で やすみます。',meaning:'I am a student. In the morning, I go to school. In the afternoon, I rest at home.',explanation:'You are now combining familiar kanji with particles and polite verbs. Read once with the guide, then once without it.',radicals:[{character:'学',meaning:'study',mnemonic:'Knowledge over a child.'},{character:'休',meaning:'rest',mnemonic:'A person by a tree.'}]}
];
